/**
 * Zabbix 系列 preset policies（6 项，2026-07-21 拆分）
 *
 * 包含：
 * - Zabbix CPU 告警自动诊断修复
 * - Zabbix 内存 / 交换分区溢出
 * - Zabbix 磁盘空间 / IO
 * - Zabbix 服务 / 进程异常
 * - Zabbix 网络连通性
 * - Zabbix 系统运行环境（时间/温度/硬件/UPS）
 *
 * 拆分原则遵循 architecture.md §3.3.1 + 第 3 条「向后兼容的 import 路径」
 */

import { v4 as uuidv4 } from 'uuid';
import type { ExtraPolicy, WorkflowIds } from './specialPolicies';

export function buildZabbixPolicies(
  ids: WorkflowIds,
  now: string,
): ExtraPolicy[] {
  const { faultDiagId, healthCheckId, fullFlowId } = ids;
  const fallbackWf = fullFlowId || faultDiagId || null;

  return [
    {
      id: uuidv4(),
      name: 'CPU 过载自动诊断修复',
      description: 'CPU 使用率/负载/iowait 告警自动诊断修复完整流程',
      alert_source: 'zabbix',
      alert_severity: null,
      alert_keywords: JSON.stringify(['cpu', 'iowait', 'load average', '处理器', 'cpu使用率', 'cpu负载', 'cpu iowait']),
      alert_tags: JSON.stringify(['performance', 'cpu']),
      execution_mode: 'auto',
      workflow_id: fallbackWf,
      workflow_params: JSON.stringify({
        server_id: '{{alert.host}}',
        collect_top_processes: true,
        top_n: 10,
        check_load_average: true,
        check_cpu_idle: true,
        save_report: true,
      }),
      max_executions_per_hour: 3,
      cooldown_seconds: 600,
      enable_verification: 0,
      verification_workflow_id: null,
      verification_params: JSON.stringify({}),
      verification_timeout_seconds: 120,
      enable_rollback: 0,
      rollback_workflow_id: null,
      rollback_on_failure: 0,
      enabled: 1,
      created_by: 'system',
      created_at: now,
      updated_at: now,
    },

    {
      id: uuidv4(),
      name: '内存/交换分区溢出自动诊断修复',
      description: '内存使用率/OOM/swap 告警自动诊断修复完整流程',
      alert_source: 'zabbix',
      alert_severity: null,
      alert_keywords: JSON.stringify(['memory', '内存', 'swap', '交换分区', 'oom', 'mem', 'out of memory', '缓存']),
      alert_tags: JSON.stringify(['performance', 'memory']),
      execution_mode: 'auto',
      workflow_id: fallbackWf,
      workflow_params: JSON.stringify({
        server_id: '{{alert.host}}',
        check_memory_usage: true,
        check_swap_usage: true,
        top_memory_processes: 10,
        check_oom_logs: true,
      }),
      max_executions_per_hour: 3,
      cooldown_seconds: 1200,
      enable_verification: 0,
      verification_workflow_id: null,
      verification_params: JSON.stringify({}),
      verification_timeout_seconds: 120,
      enable_rollback: 0,
      rollback_workflow_id: null,
      rollback_on_failure: 0,
      enabled: 1,
      created_by: 'system',
      created_at: now,
      updated_at: now,
    },

    {
      id: uuidv4(),
      name: '磁盘空间/IO 自动诊断修复',
      description: '磁盘空间不足/inode满/IO延迟告警自动诊断修复完整流程',
      alert_source: 'zabbix',
      alert_severity: null,
      alert_keywords: JSON.stringify(['disk', '磁盘', '硬盘', 'inode', 'i/o', 'io', '读写', '存储', '分区', 'mount', '空间', 'storage']),
      alert_tags: JSON.stringify(['storage', 'disk']),
      execution_mode: 'auto',
      workflow_id: fallbackWf,
      workflow_params: JSON.stringify({
        server_id: '{{alert.host}}',
        check_disk_usage: true,
        check_inode: true,
        check_disk_io: true,
        largest_dirs: 10,
      }),
      max_executions_per_hour: 3,
      cooldown_seconds: 900,
      enable_verification: 0,
      verification_workflow_id: null,
      verification_params: JSON.stringify({}),
      verification_timeout_seconds: 120,
      enable_rollback: 0,
      rollback_workflow_id: null,
      rollback_on_failure: 0,
      enabled: 1,
      created_by: 'system',
      created_at: now,
      updated_at: now,
    },

    {
      id: uuidv4(),
      name: '服务/进程异常自动诊断修复',
      description: '服务宕机/进程死亡/端口不可达自动诊断修复完整流程',
      alert_source: 'zabbix',
      alert_severity: null,
      alert_keywords: JSON.stringify(['down', 'stopped', 'unreachable', '宕机', '停止', '不可达', 'process', '进程', 'service', '服务', 'dead', 'died', 'crash', '崩溃', 'not running', 'is down', '端口']),
      alert_tags: JSON.stringify(['service', 'process']),
      execution_mode: 'auto',
      workflow_id: fallbackWf,
      workflow_params: JSON.stringify({
        server_id: '{{alert.host}}',
        check_service_status: true,
        check_process_list: true,
        check_port_listen: true,
        attempt_restart: true,
        restart_command: 'systemctl restart {{alert.service}} 2>/dev/null || true',
      }),
      max_executions_per_hour: 5,
      cooldown_seconds: 300,
      enable_verification: 1,
      verification_workflow_id: healthCheckId || null,
      verification_params: JSON.stringify({ server_id: '{{alert.host}}', verify_service: true }),
      verification_timeout_seconds: 60,
      enable_rollback: 0,
      rollback_workflow_id: null,
      rollback_on_failure: 0,
      enabled: 1,
      created_by: 'system',
      created_at: now,
      updated_at: now,
    },

    {
      id: uuidv4(),
      name: '网络连通性自动诊断修复',
      description: '网络丢包/延迟/接口故障自动诊断修复完整流程',
      alert_source: 'zabbix',
      alert_severity: null,
      alert_keywords: JSON.stringify(['network', '网络', 'ping', '丢包', '延迟', 'latency', 'traffic', '流量', '接口', 'interface', 'link', '链路', '带宽', 'bandwidth', '连接', 'connect']),
      alert_tags: JSON.stringify(['network', 'connectivity']),
      execution_mode: 'auto',
      workflow_id: fallbackWf,
      workflow_params: JSON.stringify({
        server_id: '{{alert.host}}',
        check_ping: true,
        check_interface_status: true,
        check_traffic: true,
        trace_route: true,
      }),
      max_executions_per_hour: 5,
      cooldown_seconds: 300,
      enable_verification: 1,
      verification_workflow_id: healthCheckId || null,
      verification_params: JSON.stringify({ server_id: '{{alert.host}}', check_connectivity: true }),
      verification_timeout_seconds: 120,
      enable_rollback: 0,
      rollback_workflow_id: null,
      rollback_on_failure: 0,
      enabled: 1,
      created_by: 'system',
      created_at: now,
      updated_at: now,
    },

    {
      id: uuidv4(),
      name: '系统运行环境异常诊断修复',
      description: '系统时间偏差/温度/硬件/UPS 等告警诊断修复完整流程',
      alert_source: 'zabbix',
      alert_severity: null,
      alert_keywords: JSON.stringify(['ntp', 'time', '时间', '温度', 'temperature', 'hardware', '硬件', 'ups', '电源', 'power', '风扇', 'fan', 'battery', '电池']),
      alert_tags: JSON.stringify(['system', 'hardware']),
      execution_mode: 'auto',
      workflow_id: fullFlowId || healthCheckId || null,
      workflow_params: JSON.stringify({
        server_id: '{{alert.host}}',
        check_time_sync: true,
        collect_system_info: true,
        check_dmesg_errors: true,
      }),
      max_executions_per_hour: 2,
      cooldown_seconds: 1800,
      enable_verification: 0,
      verification_workflow_id: null,
      verification_params: JSON.stringify({}),
      verification_timeout_seconds: 60,
      enable_rollback: 0,
      rollback_workflow_id: null,
      rollback_on_failure: 0,
      enabled: 1,
      created_by: 'system',
      created_at: now,
      updated_at: now,
    },
  ];
}
